name: NametagEdit
version: ${project.version}
authors: [wacossusca34, sgtcaze, sanjay900, comniemeer]
description: NametagEdit offers a great API for changing player pre- and suffixes

main: ca.wacos.nametagedit.NametagEdit